### ISSUE TITLE
TestDrive MeasureUI

### ISSUE THREAD

**Issue by tferr** [morphonets/SNT#103]
@carshadi,
Your MeasureUI is now in master. Everything seems to work as expected, but there are a couple of kinks that we may want to tweak?
Could you have a look?
One particular thing that is funky: The output column in the table becomes `Metric [Single value]'  every time the statistical n detected is 1,  to avoid generating Mean/SD/etc. columns that would host the same value. This sometimes works in an awkward way: Take the following scenarios:
1. You are analyzing a single tree and the metrics is "Cable length", statistics are "Mean" and "SD": the result appears in a `Cable length [Single value]' column, which seems suitable!?
2. You are analyzing multiple trees and the metric is. e..g., 'no. terminal branches', statistics are "Mean" and "SD" If one of the trees in the pool has only one terminal branch, then that particular tree, will be unique logged to a "No. terminal branches'. [Single value]'  column, all the others will have "No. terminal branches [Mean]", and "No. terminal branches [SD]". This does not seem intuitive, and will likely break scripts that are parsing the table?

I guess the only sane way to solve this is to get rid of the 'single value' column header logic altogether?

**Comment by carshadi** [comment]
What about keeping all the single value metrics in the old Measure dialog, and having the rest in the new one? Those could be the new "Quick Measurements". I doubt anybody uses it the way it is now with both the number of columns (the table is un-readable) and all the "Average ..." metrics.

**Comment by carshadi** [comment]
Also, super awesome! I had forgotten about this

**Comment by carshadi** [comment]
Closing this and opening new issue for the single valued metrics refactor
