### ISSUE TITLE
Cannot use measurement -> measure paths in the path manager

### ISSUE THREAD

**Issue by alexyangalexyang** [morphonets/SNT#131]
**Describe the bug**
I preferred using the path manager panel to analyze the path information. However, this function is no longer available after the current update: when I clicked on path manager -> Analyze-> measurement -> measure paths -> (choose the measure I want) -> OK : Nothing shows up.
**To Reproduce**

1. Go to 'path manager panel '
2. Click on 'Analyze'
3. Scroll down to 'measurement'
4. Choose 'measure paths'
5. Click on 'length'
6. Click ok
7. See nothing

**Comment by tferr** [comment]
Thanks for the bug report @alexyangalexyang!
We'll try to fix this for the next release.
It seems this happens only when the table is not being displayed. If ones forces the table to be displayed (e.g., by running _Analyze -> Quick measurements_ in the main dialog _before_ measuring paths), then things seem to work as expected!?

**Comment by tferr** [comment]
This should be fixed now. Not sure when it will be released though the update site, but you can download the jar manually from [here](https://maven.scijava.org/#nexus-search;gav~org.morphonets~SNT~4.1.4-SNAPSHOT~~).
