### ISSUE TITLE
Feature request: availability of video/demo datasets

### ISSUE THREAD

**Issue by Marien-kaefer** [morphonets/SNT#170]
Is the demo data that is used in video demos available for download somewhere? I mean the image {stacks}.

**Comment by tferr** [comment]
They are! 

You can access them using the File -> Load Demo Dataset...
![image](https://github.com/morphonets/SNT/assets/2439948/a082deb7-6078-40a2-81da-67e8053ba247)

Or programmatically using [SNTService](https://github.com/morphonets/SNT/blob/0b82557aa6d092a3a7b352507a7b565db5e4e759/src/main/java/sc/fiji/snt/SNTService.java#L586).

Note that some of the smallest demo files are loaded from SNT's jar (and thus part of the [source code](https://github.com/morphonets/SNT/tree/0b82557aa6d092a3a7b352507a7b565db5e4e759/src/main/resources)), while others are downloaded from the internet.

**Comment by Marien-kaefer** [comment]
Thanks, found them.
