### ISSUE TITLE
Access fitted radii and include in exported SWC file

### ISSUE THREAD

**Issue by Aman-A** [morphonets/SNT#182]
## 📚 Documentation

Hi, I'm trying to trace neurons for use in cable model simulations (e.g., in NEURON), so I want to export SWC files including the node radii. I used the Refine -> fit paths utility in the path manager and can see radius markers on all nodes, but I can't manage to export these values. They also don't seem to be recognized in SNT, as showing mean radius using Tag > Morphometry > mean radius shows 0 µm for all paths, except for paths manually assigned a radius with Edit > Specify Radius. 

This seems to be a really important and basic function, so I'm surprised I can't find anything mentioned about it in the documentation (e.g. in the Refine/Fit section of the manual), unless I'm missing something. I appreciate any help you have to offer.

**Comment by carshadi** [comment]
Hi @Aman-A ,

To have the fitted radii exported with the SWC, you just have to choose "Replace existing nodes (undoable operation)" in the fitting parameters.

![image](https://github.com/morphonets/SNT/assets/44130022/df25cdd1-087d-477f-9d35-3fac4de5c70c)

Then, when you export an SWC with _File > Save Tracings > Export as SWC..._ , the fitted radii will appear in column 6 of the SWC file, e.g.,

```
# Exported from SNT v4.2.0 on 2023-07-18T18:12:38.159
# https://imagej.net/SNT
#
# All positions and radii in µm
# Voxel separation (x,y,z): 0.32964852215271034, 0.32964852215271034, 0.9988
#
1	2	10.841535 141.789682 0.653617 1.504139	-1
2	2	10.527476 141.510011 0.949726 1.504139	1
3	2	10.223603 141.001361 1.052746 1.504139	2
4	2	10.106611 140.697331 1.421269 1.504139	3
5	2	10.013750 140.380452 1.786628 1.504139	4
6	2	9.923102 140.080963 2.169376 1.489228	5
7	2	9.848682 139.777862 2.505953 1.489228	6
```

That will also fix the issue (which is a bug) you are seeing with Tag > Morphometry > Mean Radius option.

Let me know if this resolves your issue!

**Comment by tferr** [comment]
>This seems to be a really important and basic function, so I'm surprised I can't find anything mentioned about it in the documentation

By default, anything that is "SNT-centric" such as fits and fills is only saved in TRACES files. All that gets lost when exported to SWC. We tried to make that distinction by naming commands in the GUI as _Save_ vs _Export_. But that is probably too nuanced. How could this be improved? Add these differences to this [FAQ](https://imagej.net/plugins/snt/faq#in-which-format-should-i-save-my-tracings-traces-or-swc)? I guess one could also add a warning when exporting to SWC and such features exist.

**Comment by Aman-A** [comment]
Thank you for the quick reply, @carshadi, that worked! 

My main application for the tracings is running compartmental cable model simulations, which require diameter information, so I think it would be helpful for myself and others using SNT for similar applications if it was described in the documentation how to export morphologies to SWC in a way that includes both the node coordinates and diameters. I think it's pretty clear in the software/documentation that not all the information from SNT included in the traces format will be exported to the SWC, but probably adding the information in @carshadi's answer to the the Refine/fit section would be enough. I'm actually also not sure how the fit vs. fill functions determine the radius if exported to SWC (is one or the other used?), so it would also be helpful if there were a section explaining this and then how to include these in the exported SWC file. 

Thank you!

**Comment by tferr** [comment]
I've added this to my local branch of the documentation:
![image](https://github.com/morphonets/SNT/assets/2439948/35e1db43-56a3-460b-9ca5-cd2335d815ba)

![image](https://github.com/morphonets/SNT/assets/2439948/16fa3329-2123-4422-b2ba-d47bc2bb599d)

But it may take a while to have it online. I am trying to update a bunch of outdated stuff and will try to do it in bulk.
