### ISSUE TITLE
Rename from master to main

### ISSUE THREAD

**Issue by kephale** [morphonets/SNT#183]
Just noting that SNT should rename the primary branch of the repo form `master` to `main` in order to match the current social standards.

**Comment by tferr** [comment]
Thanks a lot @kephale . Had completely forgotten about this. @carshadi, here are the instructions to rename your local repo, in case you get stuck on some weird state:

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

We should also add a code of conduct and contribution guidelines. Do let me know if you guys have good templates.
