### ISSUE TITLE
Release Strategy

### ISSUE THREAD

**Issue by tferr** [morphonets/SNT#20]
@ctrueden:

There has been quite a bit of repository tectonics around here. In a nutshell: @kephale, and I decided to create a dedicated organization for all things neuroscience[1]. The shiny new SNT is here now, as well as related projects. The major problem with releasing the new SNT in the Fiji/Java8 update site is as follows: 
To replace the old Simple_Neurite_Tracer with the new SNT _without_ breaking anything, we would have to:
1. Update TrakEM2 to use SNT
2. Release SciView through the Fiji update site (we now depend on SciView)

 (we had discussed some of this [here](https://github.com/fiji/SNT/issues/46) while back) 

Both of those require immediate action, and tight coordination between projects and Kyle feels SciView is not yet ready for major release.  What we thought instead was:
1. Release SNT/SciView  through our NeuroAnatomy and SciView update sites
2. Cut a new release of Simple_Neurite_Tracer in which its Menu entries display a dialog explaining the user that he/she has to subscribe to the above update sites to receive the new functionality. Any programmatic access to the old plugin, would work, because, well, it would still be there.
3. We would do some testing, to ensure that the SNT/SciView subscription combo, would not cause havoc for users

This way TrakEM2 keeps working, and then we buy some time to coordinate SciView/TrakEM2 releases. Do you agree? Also (pinging @acardona, @axtimwalde) Any further recommendations?

@ctrueden:, the only caveat with this is that we need pom 29.0.0 to be released, so that SciView can also be released without conflicts. What is your time frame on that? We are assuming it is imminent?

[1] This the most part worked quite well: we now have @carshadi in the team and he is now an avid Fiji developer using both Python and Java!

**Comment by ctrueden** [comment]
@tferr @kephale Just wanted to let you guys know that I did see this, and it's on my radar to respond in detail soon, after I finish work on pom-scijava 29.0.0—which yes, is imminent.

In general, this plan sounds reasonable. I have an intuition that there might be some pitfalls, which I'll ponder more closely and report back, once I scrutinize what you guys have done so far.
