### ISSUE TITLE
Feature request: enforce consistent whitespace for exported SWC files

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#203]
Currently, exported SWCs can have mixed tabs and spaces between columns, which causes some software to complain.
We should enforce single spaces between columns for better compatibility with other software.

**Comment by tferr** [comment]
Agree. Related: right now we are using `System.lineSeparator()` to separate lines. That means in `\n` in UNIX by `\r\n` in Windows. @carshadi, what about the line separator. Keep as-is?

**Comment by carshadi** [comment]
The line separator is probably fine as-is

**Comment by tferr** [comment]
They recommend [only "\n"](https://github.com/INCF/swc-specification/issues/6#issuecomment-1447294450), but I agree we can keep that as-is for now as I am not sure which scripts out there are parsing files with hardwired separators. Also, d5a784542c13ca77747cfbc143c0abbedd2fd997 adds support for the "new" SWC type flags, listed in the updated [SWC specification](https://swc-specification.readthedocs.io/en/latest/). The only issue is that some of these integers were used by FORK_POINT and END_POINT, but I think nobody was using them!?

These are the new tags:
![image](https://github.com/morphonets/SNT/assets/2439948/f4388a8f-3e32-4813-b514-cb4c0be9cdca)

**Comment by carshadi** [comment]
looks good

> The only issue is that some of these integers were used by FORK_POINT and END_POINT, but I think nobody was using them!?

 yeah, I know Janelia uses FORK_POINT==5 and END_POINT==6, but that information is already encoded in the tree structure so there is no good reason to use the type tags for them, imo.
