### ISSUE TITLE
Memory leak after SNT is closed ?

### ISSUE THREAD

**Issue by NicoKiaru** [morphonets/SNT#208]
**Describe the bug**
It looks like the memory is not released after SNT is stopped.

**To Reproduce**
Look at memory occupation ( ~60 Mb) on a fresh start. Open SNT with a ~400Mb image, trace bunch or neurons (optional?). Close SNT. Look at memory: there's still 400 Mb occupied.

**Expected behavior**
I think the memory should go back to a lower value.

**Screenshots**
I've done a mem dump with visual VM and it looks like a hashmap in SNT retains most of the memory:

![image](https://github.com/morphonets/SNT/assets/20223054/ce3f7b31-53a4-4711-8c29-39bfe070a9f6)

**Comment by tferr** [comment]
Thanks a lot for the report, @NicoKiaru!
It looks like [this](https://github.com/morphonets/SNT/blob/d5a784542c13ca77747cfbc143c0abbedd2fd997/src/main/java/sc/fiji/snt/SNT.java#L280) is the culprit. @carshadi, would you have time to look into it?

**Comment by carshadi** [comment]
I'll take a look

**Comment by carshadi** [comment]
@tferr this should be improved in #209 . The SNT plugin itself is not garbage collected presumably since several components hold references to it even after the UI is closed. However, after these changes, the plugin instance only occupies ~2KB after closing the UI.

**Comment by tferr** [comment]
This should now be fixed and #209  has been merged into main. However,  since are now compiling with Java 11, this will only be released when Fiji Java 11 becomes available. I am not sure when that will be. Hopefully soon!!
