### ISSUE TITLE
MouseLightQuerier node extraction

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#27]
Currently, `MouseLightQuerier` is having issues extracting nodes from any compartment of loaded neurons. Here is a minimial example. Note that I chose AA0100 since this neuron is used by `MLTreeTest`, and has been verfied to produce the correct node counts when downloaded with `MouseLightLoader`:
```
from sc.fiji.snt.io import (MouseLightLoader, MouseLightQuerier)

loader = MouseLightLoader("AA0100")
loader_all = loader.getNodes()
loader_axon = loader.getNodes("axon")
loader_dendrites = loader.getNodes("dendrites")

querier = MouseLightQuerier("AA0100")
querier_all = querier.getNodes()
querier_axon = querier.getNodes("axon")
querier_dendrites = querier.getNodes("dendrites")

print("all nodes: {}, {}".format(loader_all.size(), querier_all.size()))
print("axon:      {}, {}".format(loader_axon.size(), querier_axon.size()))
print("dendrites: {}, {}".format(loader_dendrites.size(), querier_dendrites.size()))
```
Outputs:
```
all nodes: 48709, 28144
axon:      20567, 6
dendrites: 28143, 28196
```
Note that the above output for `querier` is inconsistent between executions (not shown here), but `loader` always produces the same node counts.
Additionally, `MouseLightQuerier` produces this error message (but does not crash) when running the above snippet:
```
[ERROR] [SNT] Error while extracting nodes
org.json.JSONException: JSONObject["brainAreaId"] is not a string.
	at org.json.JSONObject.wrongValueFormatException(JSONObject.java:2590)
	at org.json.JSONObject.getString(JSONObject.java:863)
	at sc.fiji.snt.io.MouseLightQuerier.assignNodes(MouseLightQuerier.java:469)
	at sc.fiji.snt.io.MouseLightQuerier.getNodes(MouseLightQuerier.java:323)
```

**Comment by tferr** [comment]
Thanks. I will look into it!

**Comment by carshadi** [comment]
@tferr I have a partial fix in this PR (Sorry about the import re-arrangement, I just started using IntelliJ ;) ). However, there was another issue buried under this one which is still at large.

**Comment by carshadi** [comment]
After the commit above, the output is now _consistently_ as follows:
```
all nodes: 48709, 48711
axon:      20567, 20567
dendrites: 28143, 48711
```
So there is still an issue with the way dendrite/all nodes are extracted.

**Comment by tferr** [comment]
Thanks. I' think the rest has to do with the query itself. I'll look.

**Comment by carshadi** [comment]
@tferr should this be closed since the redundant functionality was removed from the querier?
