### ISSUE TITLE
add citation to readme

### ISSUE THREAD

**Issue by nkicg6** [morphonets/SNT#36]
Would you mind adding the current preprint to a citation section here in the readme? It took me a minute to find the current SNT citation (preprint https://www.biorxiv.org/content/10.1101/2020.07.13.179325v1)

The ImageJ wiki is locked due to the migration so I can't update it myself (https://imagej.net/SNT:_FAQ.html#citing) and I am not sure whether you all would rather we cite the original in the meantime (https://academic.oup.com/bioinformatics/article/27/17/2453/223685)?

Happy to add this if you all are busy!
Nick

**Comment by tferr** [comment]
Thanks a lot @nkicg6 ! (and sorry for the delay). It is unfortunate that the wiki is currently read-only. We added the link (and a badge) to the README. We would prefer citing https://doi.org/10.1101/2020.07.13.179325 in the interim. Thanks! (I am closing this now, but can re-open if needed)
