### ISSUE TITLE
StrahlerAnalyzer branch lengths

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#4]
There is an issue with the computation of branches in StrahlerAnalyzer.
The TreeAnalyzer metrics related to branch length, including getAvgBranchLength() and getAvgContraction() output incorrect results for the demo tree ```new SNTService().demoTree();```
Note how the SNT average branch length is not consistent with (total cable length / # branches)
Also note i removed the root node from the demo tree since NeuroM ignores the soma in their calculations, so the table results are slightly different than usual.
```
|                          | NeuroM              | SNT                |   |   |
|--------------------------|---------------------|--------------------|---|---|
| Horton-Strahler number:  | 5                   | 5                  |   |   |
| Total cable legth:       | 568.3452377915606   | 568.3452377915606  |   |   |
| Number of branches:      | 31                  | 31                 |   |   |
| Average branch length:   | 18.33371734811486   | 144.28315015537902 |   |   |
| Number of branch points: | 15                  | 15                 |   |   |
| Number of terminals:     | 16                  | 16                 |   |   |
| Total volume:            | 1785.5092237487272  | 1785.5092237487108 |   |   |
| Maximum branch order:    | 5                   | 5                  |   |   |
```
I'm pretty sure this chunk is responsible. points are added to branches based off their shared Path in the source tree. However, points may be on the same Path in the Tree but not on the same branch in the graph, and since it fetches the branch to append to by Path id, it could be appending the wrong points to the branch, which could explain the funky branch lengths.
https://github.com/morphonets/SNT/blob/31edc8c6c8a4ea6fe877461ea96e2f87bf31c7f5/src/main/java/sc/fiji/snt/analysis/StrahlerAnalyzer.java#L142-L160

I attempted to resolve this in https://github.com/morphonets/SNT/pull/5  by creating a new Path for each root in the subGraph, and traversing to the next branch or end point, appending each child in order. This appears to resolve the errors with the branch length based metrics in TreeAnalyzer, outputting the following: 

```|                          | NeuroM              | SNT                |   |   |
|--------------------------|---------------------|--------------------|---|---|
| Horton-Strahler number:  | 5                   | 5                  |   |   |
| Total cable legth:       | 568.3452377915606   | 568.3452377915606  |   |   |
| Number of branches:      | 31                  | 31                 |   |   |
| Average branch length:   | 18.33371734811486   | 18.333717348114863 |   |   |
| Number of branch points: | 15                  | 15                 |   |   |
| Number of terminals:     | 16                  | 16                 |   |   |
| Total volume:            | 1785.5092237487272  | 1785.5092237487108 |   |   |
| Maximum branch order:    | 5                   | 5                  |   |   |
```

**Comment by tferr** [comment]
Nice! This is great

**Comment by carshadi** [comment]
Keeping this open since there is another bug that https://github.com/morphonets/SNT/pull/5 introduced.... The issue is identified and a fix is imminent.

**Comment by carshadi** [comment]
Alright so made some adjustments with https://github.com/morphonets/SNT/pull/6 and tested the Strahler metrics against all neurons in the MouseLight database, including some simple test neurons i made for different edge cases. Everything seems to be in order now hopefully

**Comment by carshadi** [comment]
These issues have pointed out that the demo tree used in tests may be immune to some subtle issues that are more easily seen with asymmetric, complex trees. I can go ahead and change the TreeAnalyzer JUnit test to use one of the other demo trees (MouseLight dendrites) if that sounds good.

**Comment by tferr** [comment]
Yes, that would be perfect!

**Comment by carshadi** [comment]
closing this
