### ISSUE TITLE
Tag Template scripts

### ISSUE THREAD

**Issue by tferr** [morphonets/SNT#41]
Currently we bulk list any SNT-associated script in the GUI. Having scripts in the GUI is great but this bind approach is not optimal because some scripts are just demos that should only run from the Script Editor.

Two things can be used to improve this:
1. Label all non-GUI scripts with a tag in the filename (e.g., demo [or hacky even e.g., an "invisible" space at the end of the filename]). This way, we can then ignore those in [SciptInstaller](https://github.com/morphonets/SNT/blob/master/src/main/java/sc/fiji/snt/gui/ScriptInstaller.java) 
2. Improve the demo-tailored scripts to run with optional real data. A great example of this is e.g., [Render_Cell_Collection](https://github.com/morphonets/SNT/blob/master/src/main/resources/script_templates/Neuroanatomy/Render/Render_Cell_Collection.groovy): it runs in demo mode if the user specifies nothing.

The latter should only be done _if_ doing so does not affect readability of the script. We won't be able to do all the time, but there are good candidates for it,e.g., [Render_Cell_Collection_(Skeletonized_Montage)](https://github.com/morphonets/SNT/blob/master/src/main/resources/script_templates/Neuroanatomy/Render/Render_Cell_Collection_(Skeletonized_Montage).groovy)

@carshadi , I am assigning this to you

**Comment by tferr** [comment]
@carshadi , update:
I realized now I had actually done most of the legwork for this. The only things missing are:
1. Make sure that all the Demo scripts have been tagged properly
2. Tweak the following scripts so they can run with user data:
 - Render_Cell_Collection_(Skeletonized_Montage).groovy
 - Convert_Reconstruction_To_ROIs.groovy
 - Reconstruction_From_Skeleton.py

And i think that should be it. We shouldn't need anything else

**Comment by carshadi** [comment]
OK, the only one I'm not sure what to do with is Reconstruction_From_Skeleton.py, since it could arguably fall into the Demo category. Making it accept user data would essentially make it a copy of the utility function in the SNT GUI. What do you think?

**Comment by tferr** [comment]
As per slack conversation:  I should be OK to mod the Reconstruction_From_Skeleton.py script. It would allow for people to do stuff without using the GUI (e.g., try to see 'how it looks' to convert a skeleton').

**Comment by carshadi** [comment]
@tferr Is there anything more that needs to be done here? Otherwise I can close this

**Comment by tferr** [comment]
I think it is all good. Go ahead!
