### ISSUE TITLE
Space bar (Pan tool) shortcut not synching across views

### ISSUE THREAD

**Issue by tferr** [morphonets/SNT#43]
Reported here: https://forum.image.sc/t/snt-issue-with-the-ui/45185?u=tferr

**Comment by NicoKiaru** [comment]
It works in my hands, but the XZ and YZ panels are not synchronized with panning (they are with the zoom)

**Comment by tferr** [comment]
This seems to be working for me too (the only issue is that the cursor does not change to 'hand' immediately when I press the space bar, which arguably should be improve (i just cannot see anything immediate in the code that can cause it).
Also, there is now a new entry in the image contextual menu 'pan mode' that activates the pan mode 'full time' until. (this should make panning on a track-pad easier).

As per the syncing panes while panning. It would be nice to have it, I just don't have enough time to tackle it now. Will keep this open as a reminder.

**Comment by tferr** [comment]
Pan across panes should now be working with 063f191742
