### ISSUE TITLE
PathFitter gives non-deterministic results

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#44]
**Describe the bug**
Running _Path Manager > Refine/Fit > Fit Paths..._ produces paths with slightly different morphometric properties on each run. The differences are visible in the tracings.

**To Reproduce**
I used the OP_1.tif image with no pre-processing
1. Set fitting parameters. The params I used were:
    - **Type of refinement:** 2) Snap node coordinates to cross-section centroids
    - **Max radius:** 6 pixels
    - **Replace nodes:** replace existing nodes (undoable operation)
    - **Multithreading:** 16 threads (although the same issue occurs even when using only 1 thread)
2. Load SWC into the Path Manager
3. Run _Fit paths..._ using above params
4.  Get metrics using _Analysis > Measure..._
5. Delete all paths
6. Repeat steps 2 to 5 

**Expected behavior**
The fitting result should be the same on each call, if using the same parameters and starting with a fresh SWC

**Screenshots**
Metric results of the 4 runs, note how it also affects non-curvature related metrics such as # branches
![image](https://user-images.githubusercontent.com/44130022/100153377-03cf5180-2e72-11eb-898f-ab52de4f7318.png)

**Fiji details (If possible, please paste here the contents of _Plugins>Debug>System Information_):**
Running 3.1.111-SNAPSHOT

**Comment by tferr** [comment]
This is fixed with V4.0.0
