### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by kephale** [morphonets/SNT#66]
**Is your feature request related to a problem? Please describe.**

Put SNT on the front page of https://fiji.sc/ in the plugin box

**Comment by carshadi** [comment]
Is this the one? It shows up every once in a while, guessing the featured plugins are selected randomly on page refresh?
![image](https://user-images.githubusercontent.com/44130022/134949582-d7c11e78-313d-4424-ba93-c40e2c97e3fb.png)

**Comment by kephale** [comment]
OH! I didnt realize that the subset of plugins was randomly selected now too :D Problem solved!
