### ISSUE TITLE
DirectedWeightedGraph improvements

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#7]
This issue marks the beginning of the proposed expansions to the Graph functionality. 
Changes proposed in https://github.com/morphonets/SNT/pull/8:

- Fix typo in method signature of DirectedWeightedGraph.getTips()
- Add public method to assign Euclidean distances between adjacent vertices as edge weights
- Add public method to scale the point coordinates of the graph
- Add public method to get the sum of the edge weights of the graph
- Add public method to get a DepthFirstIterator for the graph
- Add private method to update the vertex properties of the graph
   - This method uses the current topology of the graph to re-assign the SWCPoint id, parent and previousPoint fields of each vertex. The intent is to call this method any time new objects are created from the graph (i.e, a new Tree, simplified graph, dendrogram, etc...) so that the new object will reflect any changes made to the graph structure during its lifetime.
- Change DirectedWeightedGraph.getRoot() to throw an IllegalStateException if the graph contains multiple connected components.
- Change DirectedWeightedGraph.getTree() to return a new Tree which reflects the current state of the graph (we could also add a boolean field to the graph which states whether the graph structure has changed during its lifetime, if not returning a cached copy of the original Tree the graph was created from. Of course this would require overriding all of the superclass methods which alter the graph structure).
- Add a JUnit test for DirectedWeightedGraph

Please let me know if I am missing anything, or if anything should be added/removed from this list.
@tferr

**Comment by tferr** [comment]
@carshadi, this is great!
One thing that it would be useful to have is convenience methods to access brain annotations on key elements of the graph. Something like the new TreeAnalyzer methods for [junctions](https://github.com/morphonets/SNT/commit/9039db3f5240e9c8ea2a3ff59a49fb21908fcf2a#diff-7d7872885d352067f39a8780b7a15cf8R672) and [tips](https://github.com/morphonets/SNT/commit/9039db3f5240e9c8ea2a3ff59a49fb21908fcf2a#diff-7d7872885d352067f39a8780b7a15cf8R640). These are interface-based, so they work for any brain template, mouse, fly etc. What do you think?

**Comment by carshadi** [comment]
Sounds good! anything in particular you had in mind?

**Comment by tferr** [comment]
No, we don't need to do everything now :). But as we start including BrainAnnotations, we probably have to bundle a the json file of a full projection cell (so that we have access to many compartments) and write tests for it

**Comment by carshadi** [comment]
good point

**Comment by tferr** [comment]
@carshadi , I think this is now outdated and can be closed? since  DirectedWeightedGraph  already has most of this?

**Comment by carshadi** [comment]
agreed
