### ISSUE TITLE
Feature request: Zenodo DOI

### ISSUE THREAD

**Issue by skalarproduktraum** [morphonets/SNT#83]
**Is your feature request related to a problem? Please describe.**
My institution requires data and software archiving for publications. Using [Zenodo](https://zenodo.org) to create DOIs for releases could help here :)

**Describe the solution you'd like**
Zenodo automatically creates DOIs from Github releases, only needs to be activated once, and makes each new software citeable then.

**Describe alternatives you've considered**
One alternative is manual archiving in e.g. our institute's repository. That also creates a DOI, but is a wholly manual process.

**Comment by tferr** [comment]
Hey @skalarproduktraum !! I think we have this set up already!? 

Maybe we just need to add the badge to the README?

[![DOI](https://zenodo.org/badge/221831995.svg)](https://zenodo.org/badge/latestdoi/221831995)
