### ISSUE TITLE
Bundle 'Convex Hull' batch script

### ISSUE THREAD

**Issue by tferr** [morphonets/SNT#88]
@carshadi, Would be nice to bundle your batch [script](https://forum.image.sc/t/convexhull-bulk-processing/62000/2?u=tferr)!

> Creating visualizations would require a bit more effort since there are differences when scripting the 2D vs 3D viewers.

I was thinking about this. With cffe8eec812a236ffd720a4d2aa6bf8f9fa3e286, one could use Reconstruction Viewer to render both a  Mesh or a Polygon2D. E.g.:

```python
(...)
viewer = snt.newRecViewer(True)
colors = SNTColor.getDistinctColors(len(trees))
for idx, tree in enumerate(trees):
    (...)
    tree.setColor(colors[idx])
    viewer.add(tree)
    geo_annot = Annotation3D(geo, colors[idx], tree.getLabel() + " Conv. Hull")
    viewer.add(geo_annot)
```
If too awkward, one could extend the `viewer.add(Object)` to accept directly either one without having to create an Annotation3D first?

Also, using a headless viewer `viewer = Viewer3D(False, "offscreen")`, would probably work here too, and you could have it so it saves a snapshot of the 'offscreen' scene without having it rendered.

What do you think?

**Comment by carshadi** [comment]
That would be pretty neat

**Comment by tferr** [comment]
OK. Assigned to you. :wink: The snippet above should work with the current master.

**Comment by carshadi** [comment]
Alright, it will be a little while before I can get to this though. Otherwise feel free to steal it ;)

**Comment by tferr** [comment]
No worries. I just [recycled](https://github.com/morphonets/SNT/blob/37f46a79cf2d9c2ccb192e58e46affc1364f7aed/src/main/resources/script_templates/Neuroanatomy/Batch/Convex_Hull_Bulk_Analysis.py) what you had, to make it available in the upcoming release.
