### ISSUE TITLE
Path Order inconsistency

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#9]
There is possible bug in the computation of path order. For AA0100 from the MouseLight database, TreeAnalyzer.getHighestPathOrder() yields maximum path order 31. However, NeuroM yields 34. Assuming we want to go with the centrifugal branch ordering as defined [here](https://www.mbfbioscience.com/help/nx11/Content/Branch%20order/Branch_Order.htm), the computation could be done as follows (note that NeuroM starts with path order 0):

```
from sc.fiji.snt import (Path, PathAndFillManager, SNT, SNTUI, Tree)
from sc.fiji.snt.analysis import (MultiTreeColorMapper, PathProfiler, RoiConverter,
        TreeAnalyzer, TreeColorMapper, TreeStatistics)
from sc.fiji.snt.io import (FlyCircuitLoader, MouseLightLoader, NeuroMorphoLoader)

from org.jgrapht import Graphs
# Documentation Resources: https://imagej.net/SNT:_Scripting
# SNT API: https://javadoc.scijava.org/Fiji/index.html?sc/fiji/snt/package-summary.html

tree = MouseLightLoader("AA0100").getTree()
graph = tree.getGraph()
dfs = graph.getDepthFirstIterator(graph.getRoot())
order = 0
maxOrder = 0
while dfs.hasNext():
	v = dfs.next()
	if Graphs.vertexHasPredecessors(graph,v):
		p = Graphs.predecessorListOf(graph,v)[0]
		if graph.outDegreeOf(p) > 1:
			order = p.v + 1
	v.v = order
	if order > maxOrder:
		maxOrder = order

print(maxOrder) # outputs 34
```

**Comment by carshadi** [comment]
Actually, are we using shaft ordering where the primary path is assigned order 1 @tferr ? In that case there is no issue

**Comment by carshadi** [comment]
In any case, it might not be a bad thing to have multiple schemes available...

**Comment by tferr** [comment]
Multiple schemes would be nice. But then I would create OrderAnalyzer interface and have StrahlerAnalyzer implement it. The new ones would follow the same logic. 

> Actually, are we using shaft ordering where the primary path is assigned order 1 @tferr ? In that case there is no issue

We are. But there is a discrepancy: In the Shaft ordering only "order 1" matches our "Path 1" ordering. The remaining classification is assigned on branches, and we keep assigning it to SNT Paths, that can be composed of many branches. Very confusing.

**Comment by carshadi** [comment]
I see, so in that sense it really is a true "Path" ordering. I can close this false alarm unless you feel otherwise
